frequency: 30
magnetic_declination_radians: 0.0031997697
zero_altitude: true
broadcast_cartesian_transform: true
# broadcast_cartesian_transform_as_parent_frame: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false
yaw_offset: 0.0